server.port=8080
spring.application.name=flickr-backend

# Flickr API Configuration
flickr.api.key=aa80857dbe0f4136252b8177f378d669
flickr.api.secret=658fe2bb21dc1445
flickr.api.base-url=https://api.flickr.com/services/rest/